### ISSUE TITLE
Error underline in online editor difficult to see for those with colourblindness

### ISSUE THREAD

**Issue by Keating950** [pest-parser/site#12]
Hello,

I am red-green colourblind, and finding the red dashed underline that indicates an error in the online editor is quite difficult. A different colour, such as a bright yellow, would be much easier to spot; alternatively, a thicker line or brighter shade would also be an improvement in terms of accessibility.

**Comment by tlboright** [comment]
Hey @tomtau  , what is a proposed solution that would be preferred for this issue?

Are we thinking of changing the color scheme of the textarea boxes or changing the color of the underlined text?

If it is the former, what is the preferred color of the textarea box background?

**Comment by tomtau** [comment]
@tlboright the latter I think. The former would perhaps require changing the overall page colour scheme (the colour schemes of the textarea boxes match the page background).

**Comment by Jamalam360** [comment]
Am colour-blind, also agree. might look into a PR or something

**Comment by LeoDog896** [comment]
The original codemirror styling uses a distinct and slightly bolder underline (using the wavy dash as seen in monaco editor) - should we just use the default one instead then?
![new one](https://github.com/pest-parser/site/assets/26509014/872d39fa-f4a6-4bba-a131-b0dbe72abd35)
![old one](https://github.com/pest-parser/site/assets/26509014/f12bf18d-1315-44d5-ac1b-8d809179d2e0)

**Comment by nathanielknight** [comment]
For reference, the current colours (as far as I can determine) are:

* Foreground: #5b364c
* Background: #253451

Which has a very poor contrast score: https://coolors.co/contrast-checker/5b364c-253451
