### ISSUE TITLE
Add Licence 

### ISSUE THREAD

**Issue by dffdff2423** [pest-parser/site#16]
The website seems to be missing a licence file. Is it also under MIT/Apache like the main pest repo?

**Comment by tomtau** [comment]
I'd assume so, better for @dragostis to clarify

**Comment by LeoDog896** [comment]
We should get this done ASAP - the more contributors we have the harder it would be to switch the license to MIT / Apache, especially considering that there are outside contributors (including me) who have contributed to this.

**Comment by tomtau** [comment]
> We should get this done ASAP - the more contributors we have the harder it would be to switch the license to MIT / Apache, especially considering that there are outside contributors (including me) who have contributed to this.

I got a reply back from @dragostis back in November that he'd try to add soon, and that he didn't previously add a license to the original code, because he didn't anticipate the project would become popular. 
Anyway, I just sent him a reminder and we can give it a few days (if there's no reply, we can go with the same license as on the main pest repo in the meantime).

**Comment by LeoDog896** [comment]
Once he adds the license, I _think_ we need confirmation from all of the contributors that they don't mind licensing their contributions in that license (when no license exists, [the inbound=outbound rule doesn't apply](https://github.com/github/site-policy/blob/1263bf0164cfe60d0900e70ba9126855c7c23c6c/Policies/github-terms-of-service.md#6-contributions-under-repository-license)) - so once dragostis adds the license, we need some form of approval from everyone who made non-deleted changes.

**Comment by tomtau** [comment]
got a reply from @dragostis:
> Hi Tomas,

> Feel free to do use the same license. I won't have time these days to fix the domain issue.

> Dragoș

so I'll just add the main pest repo's license
