### ISSUE TITLE
Code and tracebacks are ill-formatted on deployed site

### ISSUE THREAD

**Issue by nathanielknight** [pest-parser/site#40]
When I build the project locally the code and traceback examples on the site are properly formatted:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1239091/223182838-3ec12e7c-e649-4f9f-a238-17e8cf47fd72.png">

On the deployed site, the formatted code is missing line breaks:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/1239091/223183003-c1ef1f04-45c5-4284-ae83-2fd3648f57b9.png">

It looks like the deployed site has a bunch of whitespace removed compared to the output of the build task.

**Comment by LeoDog896** [comment]
This has to do with both parcel and the fact that there is no `pre` element to preserve whitespace. Parcel notices these `<pre>` elements and preserves the HTML whitespace. I'll see if I can make a fix for it.

**Comment by nathanielknight** [comment]
I was looking at the docs, but I wasn't sure. A quick fix might be to set `htmlnano` to not strip whitespace?

**Comment by LeoDog896** [comment]
It worked! Making a PR now.
