### ISSUE TITLE
Add label support for the online editor

### ISSUE THREAD

**Issue by NaeiKinDus** [pest-parser/site#48]
Unless I missed something the online editor does support labels (introduced by version 2.6.1) but does not show them in the result window.
It would be really nice to add support for them as it would help newcomers like me create better grammars without the need to add unneeded rules.

**Comment by Specy** [comment]
Is there some limitations (like not being able to compile it to wasm) or something similar that prevents this from being added? I'm starting to work on a lib that will be compiled to wasm and i wanted to use tags for ease of use. (also would be cool to have them in the pest website too)

**Comment by tomtau** [comment]
they are supported in pest_vm: https://github.com/pest-parser/pest/blob/master/vm/src/lib.rs#L246 so it should be possible to add it to the website

**Comment by Specy** [comment]
I'm considering trying out to add the feature, I guess I'd need to edit [Here](https://github.com/pest-parser/site/blob/b3eaf6312efad5385dd7e43b6e40f57bfb8b1ce4/src/lib.rs#L135) , what do you think would be a good output format? I was thinking:

```
- problem
  - (#objective) objective_type: "max"
  - (#lhs) sum
      - num: "1"
```
Not sure if I'll be able to add it as I'm not that good at rust but I can try

**Comment by tomtau** [comment]
@nathanielknight @Jamalam360 @huacnlee @LeoDog896 any thoughts?

**Comment by huacnlee** [comment]
I have own written a lot of Pest on this one line editor. I don't think this is a must.

But, what if you add this with a editor option for enable this?

**Comment by Jamalam360** [comment]
Yes I think that looks ok. Having a separate editor page would be nice but not essential
