### ISSUE TITLE
Make online editor full page

### ISSUE THREAD

**Issue by markmmm** [pest-parser/site#6]
The online editor at pest.rs is a amazing feature for me. It allowed me to:
* See how easy it is to start creating rules
* Debug my rules with my content

The request I have is to have a button/page to make it full screen. (I have currently hacked the boxes in firefox to give me more room.). If easy - then maybe make the boxes resizable (often the rules can be made smaller - as I am focusing on a small subset of the whole grammar.
Why:
* Have less wrapping - makes it easier to see the rules, content to parse more easily.
* Having more vertical width let's me see more of everything (especially the output usually)

Thank you for Pest - I love it!

**Comment by dragostis** [comment]
Thanks for the issue! I completely agree, however, I have been focusing on other stuff lately. If you have the time, I would be more than happy to accept improvements to the editor experience.

**Comment by singalen** [comment]
+1. Would also be nice to make text areas resizeable.
