### ISSUE TITLE
Share button depends on discontinued service

### ISSUE THREAD

**Issue by nathanielknight** [pest-parser/site#9]
The Share button for the online editor depends on myjson.com, but it appears that that service has been discontinued.

**Comment by singalen** [comment]
Is this the reason why old editor snippet references are not working, or is that a separate issue?

**Comment by CAD97** [comment]
Yep, this is the reason that share links no longer work.

**Comment by nathanielknight** [comment]
This could probably be fixed by base64-encoding the data and storing it in the URL (though it would make for big URLs if the grammar is big). It might be a hassle to make it backwards compatible, but that might not matter if old links won't work anyways?

I could take a stab at this if it would be of interest.

**Comment by tomtau** [comment]
or use another service (e.g. https://jsonserve.com )?
